version: 2.0
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
          name: Restore node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
              echo 'Installing npm dependencies'
              npm ci
            fi
      - save_cache:
          name: Save node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: |
            echo 'Running tests'
            npm test
workflows:
  version: 2
  test:
    jobs:
      - test
